exclude: null
grid-search:

  "--config":
    - "dvdn_ns"

  lr:
    - 0.001
    - 0.003
    - 0.005

  common_reward:
    - True

  q_target_consensus:
    - False

  target_update_interval_or_tau:
    - 20
    - 0.01

  hidden_dim:
    - 64
    - 128

  evaluation_epsilon:
    - 0.0
    - 0.05

  epsilon_anneal_time:
    - 180_000
    - 230_000

  epsilon_finish: 
    - 0.05
    - 0.01

  n_consensus_steps:
    - 1
    - 30

  t_max:
    - 288_000

  save_model:
    - false
    
grid-search-groups:
  env0:
    - "--env-config": "resco"
    - env_args.key: resco_benchmark:cologne8-dvdn_ns-v1 
    - env_args.time_limit: 360
    - env_args.save_logs: False

