# --- IQL NS specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.01
epsilon_anneal_time: 230_000
evaluation_epsilon: 0.05
hidden_dim: 128
hypergroup: hp_grp_95
lr: 0.005
# update the target network every {} episodes
target_update_interval_or_tau: 0.01

runner: "episode"

buffer_size: 5000
batch_size: 32



obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

common_reward: True

# use the Q_Learner to train
mac: "non_shared_mac"
agent: "cnn_ns"
agent_output_type: "q"
learner: "q_learner"
standardise_returns: False
standardise_rewards: True
double_q: True
use_rnn: False
mixer: # Mixer becomes None

name: "iql_ns"
t_max: 288_000 
