env: "resco"

env_args:
  key: null
  time_limit: 360
  pretrained_wrapper: null
  tr: 0

test_greedy: True
test_nepisode: 100
test_interval:  1_000_000 
log_interval: 3600
runner_log_interval: 3600
learner_log_interval: 3600
t_max: 244_000

