env: "resco"

env_args:
  key: null
  time_limit: 360
  pretrained_wrapper: null
  tr: 0
  save_logs: True

test_greedy: True
test_nepisode: 100
test_interval:  7_200
log_interval: 3600
runner_log_interval: 3600
learner_log_interval: 3600
t_max: 288_000

